### ISSUE TITLE
发送rclone相关命令无反应

### ISSUE THREAD

**Issue by zzzqu** [666wcy/ARPT-Bot#1]
其他命令可以，rclone不行，配置文件已经放进去了，按照readme里面的两处都放了

**Comment by 666wcy** [comment]
我这边测试正常，你的命令格式是怎么样

![Screenshot_2021-06-29-00-21-43-286_ir.ilmili.telegraph.jpg](https://user-images.githubusercontent.com/40867688/123670657-0ed0d280-d803-11eb-87b2-50cbe217b997.jpg)

**Comment by 666wcy** [comment]
有人反馈同样的问题，推测是自动打包时docker没有成功安装rclone，后续版本会修复

**Comment by zzzqu** [comment]
> 有人反馈同样的问题，推测是自动打包时docker没有成功安装rclone，后续版本会修复

静候佳音，希望可以支持gclone sa

**Comment by 666wcy** [comment]
最新版本的已经支持，gclone开源项目做的蛮好的，不一定会添加
