### ISSUE TITLE
ARM用docker运行bot报错

### ISSUE THREAD

**Issue by 12123ads** [666wcy/ARPT-Bot#10]
系统是Debian GNU/Linux 10 (buster) aarch64
报错：
=========================================================================
root@instance-20210810-2113:~# docker logs 74932b6833a4a003151bf2a855cbc44ce759e9907be7867ca5d6919135d108dc
--2021-08-19 13:59:41--  http://git.io/tracker.sh
Resolving git.io (git.io)... 35.153.244.194, 54.84.165.132, 34.226.109.249, ...
Connecting to git.io (git.io)|35.153.244.194|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://git.io/tracker.sh [following]
--2021-08-19 13:59:41--  https://git.io/tracker.sh
Connecting to git.io (git.io)|35.153.244.194|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/P3TERX/aria2_perfect_config/master/tracker.sh [following]
--2021-08-19 13:59:42--  https://raw.githubusercontent.com/P3TERX/aria2_perfect_config/master/tracker.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4612 (4.5K) [text/plain]
Saving to: 'tracker.sh'

     0K ....                                                  100% 45.1M=0s

2021-08-19 13:59:42 (45.1 MB/s) - 'tracker.sh' saved [4612/4612]

08/19 13:59:42 [INFO] Get BT trackers...

--------------------[BitTorrent Trackers]--------------------
http://1337.abcvg.info:80/announce,http://78.30.254.12:2710/announce,http://[2001:1b10:1000:8101:0:242:ac11:2]:6969/announce,http://[2001:470:1:189:0:1:2:3]:6969/announce,http://[2a04:ac00:1:3dd8::1:2710]:2710/announce,http://bt.rghost.net:80/announce,http://carbon-bonsai-621.appspot.com:80/announce,http://explodie.org:6969/announce,http://fosstorrents.com:6969/announce,http://fxtt.ru:80/announce,http://googer.cc:1337/announce,http://h4.trakx.nibba.trade:80/announce,http://kinorun.com:80/announce.php,http://milanesitracker.tekcities.com:80/announce,http://ns349743.ip-91-121-106.eu:80/announce,http://nyaa.tracker.wf:7777/announce,http://open.acgnxtracker.com:80/announce,http://opentracker.xyz:80/announce,http://retracker.hotplug.ru:2710/announce,http://retracker.sevstar.net:2710/announce,http://retracker.spark-rostov.ru:80/announce,http://retracker.telecom.by:80/announce,http://share.camoe.cn:8080/announce,http://siambit.com:80/announce.php,http://t.acg.rip:6699/announce,http://t.nyaatracker.com:80/announce,http://torrent-team.net:80/announce.php,http://torrentzilla.org:80/announce,http://torrentzilla.org:80/announce.php,http://tr.cili001.com:8070/announce,http://tr.kxmp.cf:80/announce,http://tracker.birkenwald.de:6969/announce,http://tracker.bittor.pw:1337/announce,http://tracker.bt4g.com:2095/announce,http://tracker.corpscorp.online:80/announce,http://tracker.etree.org:6969/announce,http://tracker.files.fm:6969/announce,http://tracker.gbitt.info:80/announce,http://tracker.grepler.com:6969/announce,http://tracker.ipv6tracker.org:80/announce,http://tracker.ipv6tracker.ru:80/announce,http://tracker.noobsubs.net:80/announce,http://tracker.opentrackr.org:1337/announce,http://tracker.tfile.me:80/announce,http://tracker.trackerfix.com:80/announce,http://tracker1.bt.moack.co.kr:80/announce,http://tracker2.dler.org:80/announce,http://vps02.net.orel.ru:80/announce,http://www.shnflac.net:80/announce.php,http://www.zone-torrent.net:80/announce.php,https://1337.abcvg.info:443/announce,https://carbon-bonsai-621.appspot.com:443/announce,https://mytracker.fly.dev:443/announce,https://open.kickasstracker.com:443/announce,https://opentracker.acgnx.se:443/announce,https://opentracker.xyz:443/announce,https://tr.torland.ga:443/announce,https://tracker.bt-hash.com:443/announce,https://tracker.kuroy.me:443/announce,https://tracker.nanoha.org:443/announce,https://tracker.nitrix.me:443/announce,https://tracker.tamersunion.org:443/announce,https://trakx.herokuapp.com:443/announce,udp://212.1.226.176:2710/announce,udp://52.58.128.163:6969/announce,udp://78.30.254.12:2710/announce,udp://9.rarbg.com:2800/announce,udp://9.rarbg.me:2710/announce,udp://9.rarbg.to:2710/announce,udp://91.216.110.52:451/announce,udp://[2001:1b10:1000:8101:0:242:ac11:2]:6969/announce,udp://[2001:470:1:189:0:1:2:3]:6969/announce,udp://[2a03:7220:8083:cd00::1]:451/announce,udp://[2a04:ac00:1:3dd8::1:2710]:2710/announce,udp://[2a0f:e586:f:f::220]:6969/announce,udp://abufinzio.monocul.us:6969/announce,udp://app.icon256.com:8000/announce,udp://bms-hosxp.com:6969/announce,udp://bt.100.pet:2711/announce,udp://bubu.mapfactor.com:6969/announce,udp://code2chicken.nl:6969/announce,udp://discord.heihachi.pw:6969/announce,udp://engplus.ru:6969/announce,udp://exodus.desync.com:6969/announce,udp://explodie.org:6969/announce,udp://fe.dealclub.de:6969/announce,udp://ipv6.tracker.zerobytes.xyz:16661/announce,udp://mail.realliferpg.de:6969/announce,udp://movies.zsw.ca:6969/announce,udp://mts.tvbit.co:6969/announce,udp://open.demonii.com:1337/announce,udp://open.stealth.si:80/announce,udp://opentor.org:2710/announce,udp://p4p.arenabg.com:1337/announce,udp://peerfect.org:6969/announce,udp://pow7.com:80/announce,udp://retracker.hotplug.ru:2710/announce,udp://retracker.lanta-net.ru:2710/announce,udp://retracker.netbynet.ru:2710/announce,udp://retracker.nts.su:2710/announce,udp://retracker.sevstar.net:2710/announce,udp://thetracker.org:80/announce,udp://tracker-de.ololosh.space:6969/announce,udp://tracker.0x.tf:6969/announce,udp://tracker.aletorrenty.pl:2710/announce,udp://tracker.altrosky.nl:6969/announce,udp://tracker.army:6969/announce,udp://tracker.beeimg.com:6969/announce,udp://tracker.birkenwald.de:6969/announce,udp://tracker.bitsearch.to:1337/announce,udp://tracker.bittor.pw:1337/announce,udp://tracker.blacksparrowmedia.net:6969/announce,udp://tracker.breizh.pm:6969/announce,udp://tracker.coppersurfer.tk:6969/announce,udp://tracker.cyberia.is:6969/announce,udp://tracker.dler.com:6969/announce,udp://tracker.eddie4.nl:6969/announce,udp://tracker.filemail.com:6969/announce,udp://tracker.flashtorrents.org:6969/announce,udp://tracker.grepler.com:6969/announce,udp://tracker.halfchub.club:6969/announce,udp://tracker.kuroy.me:5944/announce,udp://tracker.leech.ie:1337/announce,udp://tracker.leechers-paradise.org:6969/announce,udp://tracker.moeking.eu.org:6969/announce,udp://tracker.moeking.me:6969/announce,udp://tracker.monitorit4.me:6969/announce,udp://tracker.nrx.me:6969/announce,udp://tracker.ololosh.space:6969/announce,udp://tracker.opentrackr.org:1337/announce,udp://tracker.sktorrent.net:6969/announce,udp://tracker.skyts.net:6969/announce,udp://tracker.swateam.org.uk:2710/announce,udp://tracker.theoks.net:6969/announce,udp://tracker.tiny-vps.com:6969/announce,udp://tracker.torrent.eu.org:451/announce,udp://tracker.tvunderground.org.ru:3218/announce,udp://tracker.uw0.xyz:6969/announce,udp://tracker.vanitycore.co:6969/announce,udp://tracker.zerobytes.xyz:1337/announce,udp://tracker0.ufibox.com:6969/announce,udp://tracker1.bt.moack.co.kr:80/announce,udp://tracker2.christianbro.pw:6969/announce,udp://tracker2.dler.com:80/announce,udp://tracker4.itzmx.com:2710/announce,udp://vibe.community:6969/announce,udp://vibe.sleepyinternetfun.xyz:1738/announce,udp://wassermann.online:6969/announce,udp://www.torrent.eu.org:451/announce,wss://tracker.openwebtorrent.com:443/announce
--------------------[BitTorrent Trackers]--------------------

08/19 13:59:42 [INFO] Adding BT trackers to Aria2 configuration file /root/.aria2/aria2.conf ...

08/19 13:59:42 [INFO] BT trackers successfully added to Aria2 configuration file !
Traceback (most recent call last):
  File "/bot/main.py", line 4, in <module>
    from modules.check import new_clock, second_clock
  File "/bot/modules/check.py", line 1, in <module>
    from config import aria2,App_title
  File "/bot/config.py", line 36, in <module>
    client = Client("my_bot", bot_token=Telegram_bot_api,
  File "/usr/local/lib/python3.8/dist-packages/pyromod/listen/listen.py", line 40, in __init__
    self.old__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/client.py", line 207, in __init__
    self.api_id = int(api_id) if api_id else None
ValueError: invalid literal for int() with base 10: 'xxx'
mkdir: cannot create directory '/.config/': File exists
mkdir: cannot create directory '/.config/rclone': File exists
URL transformed to HTTPS due to an HSTS policy
--2021-08-19 14:05:29--  https://git.io/tracker.sh
Resolving git.io (git.io)... 34.203.159.69, 54.209.131.108, 44.196.181.185, ...
Connecting to git.io (git.io)|34.203.159.69|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/P3TERX/aria2_perfect_config/master/tracker.sh [following]
--2021-08-19 14:05:30--  https://raw.githubusercontent.com/P3TERX/aria2_perfect_config/master/tracker.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4612 (4.5K) [text/plain]
Saving to: 'tracker.sh.1'

     0K ....                                                  100% 48.9M=0s

2021-08-19 14:05:30 (48.9 MB/s) - 'tracker.sh.1' saved [4612/4612]

08/19 14:05:30 [INFO] Get BT trackers...

--------------------[BitTorrent Trackers]--------------------
http://1337.abcvg.info:80/announce,http://78.30.254.12:2710/announce,http://[2001:1b10:1000:8101:0:242:ac11:2]:6969/announce,http://[2001:470:1:189:0:1:2:3]:6969/announce,http://[2a04:ac00:1:3dd8::1:2710]:2710/announce,http://bt.rghost.net:80/announce,http://carbon-bonsai-621.appspot.com:80/announce,http://explodie.org:6969/announce,http://fosstorrents.com:6969/announce,http://fxtt.ru:80/announce,http://googer.cc:1337/announce,http://h4.trakx.nibba.trade:80/announce,http://kinorun.com:80/announce.php,http://milanesitracker.tekcities.com:80/announce,http://ns349743.ip-91-121-106.eu:80/announce,http://nyaa.tracker.wf:7777/announce,http://open.acgnxtracker.com:80/announce,http://opentracker.xyz:80/announce,http://retracker.hotplug.ru:2710/announce,http://retracker.sevstar.net:2710/announce,http://retracker.spark-rostov.ru:80/announce,http://retracker.telecom.by:80/announce,http://share.camoe.cn:8080/announce,http://siambit.com:80/announce.php,http://t.acg.rip:6699/announce,http://t.nyaatracker.com:80/announce,http://torrent-team.net:80/announce.php,http://torrentzilla.org:80/announce,http://torrentzilla.org:80/announce.php,http://tr.cili001.com:8070/announce,http://tr.kxmp.cf:80/announce,http://tracker.birkenwald.de:6969/announce,http://tracker.bittor.pw:1337/announce,http://tracker.bt4g.com:2095/announce,http://tracker.corpscorp.online:80/announce,http://tracker.etree.org:6969/announce,http://tracker.files.fm:6969/announce,http://tracker.gbitt.info:80/announce,http://tracker.grepler.com:6969/announce,http://tracker.ipv6tracker.org:80/announce,http://tracker.ipv6tracker.ru:80/announce,http://tracker.noobsubs.net:80/announce,http://tracker.opentrackr.org:1337/announce,http://tracker.tfile.me:80/announce,http://tracker.trackerfix.com:80/announce,http://tracker1.bt.moack.co.kr:80/announce,http://tracker2.dler.org:80/announce,http://vps02.net.orel.ru:80/announce,http://www.shnflac.net:80/announce.php,http://www.zone-torrent.net:80/announce.php,https://1337.abcvg.info:443/announce,https://carbon-bonsai-621.appspot.com:443/announce,https://mytracker.fly.dev:443/announce,https://open.kickasstracker.com:443/announce,https://opentracker.acgnx.se:443/announce,https://opentracker.xyz:443/announce,https://tr.torland.ga:443/announce,https://tracker.bt-hash.com:443/announce,https://tracker.kuroy.me:443/announce,https://tracker.nanoha.org:443/announce,https://tracker.nitrix.me:443/announce,https://tracker.tamersunion.org:443/announce,https://trakx.herokuapp.com:443/announce,udp://212.1.226.176:2710/announce,udp://52.58.128.163:6969/announce,udp://78.30.254.12:2710/announce,udp://9.rarbg.com:2800/announce,udp://9.rarbg.me:2710/announce,udp://9.rarbg.to:2710/announce,udp://91.216.110.52:451/announce,udp://[2001:1b10:1000:8101:0:242:ac11:2]:6969/announce,udp://[2001:470:1:189:0:1:2:3]:6969/announce,udp://[2a03:7220:8083:cd00::1]:451/announce,udp://[2a04:ac00:1:3dd8::1:2710]:2710/announce,udp://[2a0f:e586:f:f::220]:6969/announce,udp://abufinzio.monocul.us:6969/announce,udp://app.icon256.com:8000/announce,udp://bms-hosxp.com:6969/announce,udp://bt.100.pet:2711/announce,udp://bubu.mapfactor.com:6969/announce,udp://code2chicken.nl:6969/announce,udp://discord.heihachi.pw:6969/announce,udp://engplus.ru:6969/announce,udp://exodus.desync.com:6969/announce,udp://explodie.org:6969/announce,udp://fe.dealclub.de:6969/announce,udp://ipv6.tracker.zerobytes.xyz:16661/announce,udp://mail.realliferpg.de:6969/announce,udp://movies.zsw.ca:6969/announce,udp://mts.tvbit.co:6969/announce,udp://open.demonii.com:1337/announce,udp://open.stealth.si:80/announce,udp://opentor.org:2710/announce,udp://p4p.arenabg.com:1337/announce,udp://peerfect.org:6969/announce,udp://pow7.com:80/announce,udp://retracker.hotplug.ru:2710/announce,udp://retracker.lanta-net.ru:2710/announce,udp://retracker.netbynet.ru:2710/announce,udp://retracker.nts.su:2710/announce,udp://retracker.sevstar.net:2710/announce,udp://thetracker.org:80/announce,udp://tracker-de.ololosh.space:6969/announce,udp://tracker.0x.tf:6969/announce,udp://tracker.aletorrenty.pl:2710/announce,udp://tracker.altrosky.nl:6969/announce,udp://tracker.army:6969/announce,udp://tracker.beeimg.com:6969/announce,udp://tracker.birkenwald.de:6969/announce,udp://tracker.bitsearch.to:1337/announce,udp://tracker.bittor.pw:1337/announce,udp://tracker.blacksparrowmedia.net:6969/announce,udp://tracker.breizh.pm:6969/announce,udp://tracker.coppersurfer.tk:6969/announce,udp://tracker.cyberia.is:6969/announce,udp://tracker.dler.com:6969/announce,udp://tracker.eddie4.nl:6969/announce,udp://tracker.filemail.com:6969/announce,udp://tracker.flashtorrents.org:6969/announce,udp://tracker.grepler.com:6969/announce,udp://tracker.halfchub.club:6969/announce,udp://tracker.kuroy.me:5944/announce,udp://tracker.leech.ie:1337/announce,udp://tracker.leechers-paradise.org:6969/announce,udp://tracker.moeking.eu.org:6969/announce,udp://tracker.moeking.me:6969/announce,udp://tracker.monitorit4.me:6969/announce,udp://tracker.nrx.me:6969/announce,udp://tracker.ololosh.space:6969/announce,udp://tracker.opentrackr.org:1337/announce,udp://tracker.sktorrent.net:6969/announce,udp://tracker.skyts.net:6969/announce,udp://tracker.swateam.org.uk:2710/announce,udp://tracker.theoks.net:6969/announce,udp://tracker.tiny-vps.com:6969/announce,udp://tracker.torrent.eu.org:451/announce,udp://tracker.tvunderground.org.ru:3218/announce,udp://tracker.uw0.xyz:6969/announce,udp://tracker.vanitycore.co:6969/announce,udp://tracker.zerobytes.xyz:1337/announce,udp://tracker0.ufibox.com:6969/announce,udp://tracker1.bt.moack.co.kr:80/announce,udp://tracker2.christianbro.pw:6969/announce,udp://tracker2.dler.com:80/announce,udp://tracker4.itzmx.com:2710/announce,udp://vibe.community:6969/announce,udp://vibe.sleepyinternetfun.xyz:1738/announce,udp://wassermann.online:6969/announce,udp://www.torrent.eu.org:451/announce,wss://tracker.openwebtorrent.com:443/announce
--------------------[BitTorrent Trackers]--------------------

08/19 14:05:30 [INFO] Adding BT trackers to Aria2 configuration file /root/.aria2/aria2.conf ...

08/19 14:05:30 [INFO] BT trackers successfully added to Aria2 configuration file !
Traceback (most recent call last):
  File "/bot/main.py", line 4, in <module>
    from modules.check import new_clock, second_clock
  File "/bot/modules/check.py", line 1, in <module>
    from config import aria2,App_title
  File "/bot/config.py", line 36, in <module>
    client = Client("my_bot", bot_token=Telegram_bot_api,
  File "/usr/local/lib/python3.8/dist-packages/pyromod/listen/listen.py", line 40, in __init__
    self.old__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/client.py", line 207, in __init__
    self.api_id = int(api_id) if api_id else None
ValueError: invalid literal for int() with base 10: 'xxx'
root@instance-20210810-2113:~#

**Comment by 666wcy** [comment]
看起来像Bot登录时出现问题，docker运行时Api_id这项是不是加了双引号
