### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by yangchris4** [666wcy/ARPT-Bot#11]
感谢大佬分享的项目，我为啥输入命令后全部显示 **list index out of range**
![微信截图_20210822205319](https://user-images.githubusercontent.com/13220804/130356033-cc76591b-8342-4d93-b33f-3c4774462cf9.png)

**Comment by Dover715** [comment]
你后面没有输入内容。

比如说 /searchsong 一生有你

**Comment by yangchris4** [comment]
> 你后面没有输入内容。
> 
> 比如说 /searchsong 一生有你

好的，可以啦 感谢
