### ISSUE TITLE
希望支持批量下载或者上传的操作

### ISSUE THREAD

**Issue by Dover715** [666wcy/ARPT-Bot#14]
默认 /downtgfile命令下只能上传接收到的第一个文件。如果想上传多个文件的话就很麻烦。能否改为上传全部接收到的文件，直到我发送/cancel为止。
添加下载任务也是一样。希望大佬能修改一下。谢谢

**Comment by 666wcy** [comment]
批量磁力最新版本已支持，文件要到下版本

**Comment by Dover715** [comment]
> 批量磁力最新版本已支持，文件要到下版本

谢谢

**Comment by Dover715** [comment]
> 批量磁力最新版本已支持，文件要到下版本

大佬，2.0.7直接添加磁力链接卡100%不上传
![IMG_20210903_192557](https://user-images.githubusercontent.com/44842449/131998078-204cb3df-b434-49ab-ba9d-00a29357eeb6.jpg)

**Comment by 666wcy** [comment]
[v2.0.8](https://github.com/666wcy/ARPT-Bot/commit/a35a4bdbab90c657514dbe034694d3d70b66d268)已添加
