### ISSUE TITLE
下载、上传卡百分比

### ISSUE THREAD

**Issue by xxyyyx** [666wcy/ARPT-Bot#2]
好像几乎所有下载都会卡在95%左右

**Comment by 666wcy** [comment]
截图说明

**Comment by xxyyyx** [comment]
![)%`OUZ7 MJW ZMUBX E8FID](https://user-images.githubusercontent.com/42132468/127741926-42006e3d-50bf-4c65-b772-7c114cd906d4.png)
用的是gdshare的google drive 直链

**Comment by 666wcy** [comment]
实际会上传到网盘么，还是卡死也不进行上传操作

**Comment by xxyyyx** [comment]
不会上传 卡死

**Comment by railwcode** [comment]
> 好像几乎所有下载都会卡在95%左右

我这边有时od上传会卡100%

**Comment by xxyyyx** [comment]
小一年了 今天重新试了下 还是有卡的状况。。。
