### ISSUE TITLE
请问如何设置群组ID

### ISSUE THREAD

**Issue by Dover715** [666wcy/ARPT-Bot#23]
请问如何设置群组ID
是直接把星号的位置替换为群组ID就可以了吗？前面需要改一下吗？
-e Telegram_user_id=******* \

**Comment by 666wcy** [comment]
不需要，直接设置为群组ID

**Comment by Dover715** [comment]
> 不需要，直接设置为群组ID

感谢大佬回复，我直接设置群组ID之后在群组发送命令，结果收到BOT单独回复"没有使用权限"请问如何解决呀
![upload_2021_09_23_18_03_27_834](https://user-images.githubusercontent.com/44842449/134489122-96007510-16ab-4c09-9059-25163c5ebcf2.jpg)
![upload_2021_09_23_18_04_28_563](https://user-images.githubusercontent.com/44842449/134489256-631e93ab-7582-4244-8868-a4812bbac356.jpg)

**Comment by 666wcy** [comment]
检查群组ID是否正确以及Bot是否在群内(需设置管理员权限来获取成员列表)

**Comment by Dover715** [comment]
解决了，谢谢大佬。

**Comment by aiastia** [comment]
设置群组id 私聊有回应 在群里没有回应。 这个是正常的吗

**Comment by cachexy123** [comment]
> 设置群组id 私聊有回应 在群里没有回应。 这个是正常的吗

卧槽,我也是这样
