### ISSUE TITLE
2.0.9卡在100%不上传

### ISSUE THREAD

**Issue by Dover715** [666wcy/ARPT-Bot#24]
如题，V2.0.9下载的磁力会卡在100%，没有自动调用rclone上传。rclone盘符测试没有错误。

![upload_2021_09_24_00_53_09_588](https://user-images.githubusercontent.com/44842449/134550424-0dd785b4-f063-480a-a70a-82405cdb6e5d.jpg)
![upload_2021_09_24_00_54_37_553](https://user-images.githubusercontent.com/44842449/134550642-e91816ce-ac99-4a68-ab16-8528ffda87b7.jpg)

**Comment by 666wcy** [comment]
目前的概率性问题
![Screenshot_2021-09-24-09-47-03-499_nekox.messenger.jpg](https://user-images.githubusercontent.com/40867688/134608426-38c39516-0b86-4d7f-9817-c21e217c0553.jpg)
检查一下网盘中是否有上传的文件，或者换个磁力看看，如果一直这样可以把相关磁力发我看看

**Comment by Dover715** [comment]
我这里的情况是所有的磁力都不能正常上传，并且直接发送文件以后bot也没有反应，目前仅尝试了这两个。
看到更新说明里提到更换了调用rclone的方式，是否是安装bot之后除了设置rclone盘符以外还需要配置其它的东西？小白不太了解这个，请大佬帮助。

**Comment by 666wcy** [comment]
重启容器看看，另外注意你有两个相同的上传文件夹(大小写不同)，可以试试看将上传文件夹修改看看是否成功

**Comment by Dover715** [comment]
重启容器，并且修改了其中一个文件夹的名字只保留了上传文件夹。
使用/downtgfile 功能尝试上传一个文件，没有成功。日志如下
![upload_2021_09_24_13_43_26_922](https://user-images.githubusercontent.com/44842449/134624152-cceaef98-2b9f-45e3-9dcc-ffab7d6cdf6f.jpg)

这个图片截的不太清楚😂

**Comment by 666wcy** [comment]
我的问题，已提交修复，请重启查看是否成功

**Comment by Dover715** [comment]
问题已经解决，辛苦了，谢谢。
