### ISSUE TITLE
代理支持

### ISSUE THREAD

**Issue by SukiEva** [666wcy/ARPT-Bot#25]
希望能够支持代理，方便国内服务器使用

**Comment by 666wcy** [comment]
rclone本身支持代理，参见[源文档](https://rclone.org/faq/#can-i-use-rclone-with-an-http-proxy)
只需在docker开启容器时添加变量
例如：
`-e http_proxy=“http://proxyserver:12345”`

**Comment by SukiEva** [comment]
> rclone本身支持代理，参见[源文档](https://rclone.org/faq/#can-i-use-rclone-with-an-http-proxy)
> 只需在docker开启容器时添加变量
> 例如：
> `-e http_proxy=“http://proxyserver:12345”`

请问环境变量在 bot 交互时也能用嘛，主要用来请求 telegram api 时需要走代理😮

**Comment by 666wcy** [comment]
目前不支持
