### ISSUE TITLE
用和/clone有关的命令机器人没反应

### ISSUE THREAD

**Issue by hbxnlsy123** [666wcy/ARPT-Bot#27]

**Comment by hbxnlsy123** [comment]
rclone 不在运行
检查使用权限
rclone :list index out of range

**Comment by 666wcy** [comment]
尝试一下 /rclone 盘符:
之前的说明有些问题

**Comment by hbxnlsy123** [comment]
> 尝试一下 /rclone 盘符:
> 之前的说明有些问题

执行 /rclone 盘符:
也是上面那个报错
