### ISSUE TITLE
大佬能不能添加下tg频道批量下载

### ISSUE THREAD

**Issue by beer-on-ice** [666wcy/ARPT-Bot#28]
类似这个https://github.com/snow922841/telegram_channel_downloader，能下载整个频道的

**Comment by xepo12** [comment]
应该是支持的。有个源码是可以的 https://github.com/pawamoy/aria2p

**Comment by 666wcy** [comment]
bot的api不支持从频道下载，需要登录账号，在已有轮子的情况下不考虑添加
