### ISSUE TITLE
[feature request]使用磁力或种子下载前选择下载哪些文件

### ISSUE THREAD

**Issue by ckn4** [666wcy/ARPT-Bot#30]
1、有时候只需要下载其中的某几个文件，而且有些种子会带有大量用于宣传的无用文件，这样会给刮削带来困难。希望在下载开始前在bot菜单中能够选择下载哪些文件，类似于[这种的](https://github.com/gaowanliang/DownloadBot/blob/main/img/3.jpg)。
2、Anime搜图功能不知道能不能像原版一样支持gif的查询。
3、下载Tg文件时能否发送到aria2中使用多线程下载。
感谢开发者。

**Comment by ckn4** [comment]
还有一个小小的问题，Anime搜图功能不知道能不能像原版一样支持gif的查询。

**Comment by 666wcy** [comment]
会考虑，但做的可能性不大
