### ISSUE TITLE
youtube-dl限速，调整调用youtube-dlp？

### ISSUE THREAD

**Issue by jianmingd** [666wcy/ARPT-Bot#31]
youtube-dl下载速度<60KB，更改调用YouTube-dlp？
YouTube-dlp暂时不限速，很好用啊，

**Comment by 666wcy** [comment]
v2.1.0 版本后已更改为youtube-dlp

**Comment by jianmingd** [comment]
> v2.1.0 版本后已更改为 youtube-dlp

上午重新安装了一下，还是不行，(换了两台机器测试)
 File "/bot/modules/video.py", line 4, in <module>
    import youtube_dl
ModuleNotFoundError: No module named 'youtube_dl'
调用没改过来？
我是小白，尝试更改后，没改明白，所以还是提交给大佬试试吧，

还有一个问题就是下载B站播放列表，貌似一直下载的是第一个视频，

麻烦大佬抽空测试一下。

**Comment by 666wcy** [comment]
错误已提交修复，播放列表还没有做适配
