### ISSUE TITLE
这个可否换用fclone替代rclone?

### ISSUE THREAD

**Issue by xueshan367** [666wcy/ARPT-Bot#34]
这个可否换用fclone替代rclone?

**Comment by Jonathon52306** [comment]
> 可自行替换rclone文件为fclone，然后将fclone重命名为rclone，只提供这个思路，不保证成功

可以这样 我试过 但是区别不大 种子下载完该不上传就是不上传......
种子这个也是个大问题

**Comment by xsm123006** [comment]
> 可以替换rclone文件为fclone，然后将fclone重命名为rclone，只提供这个思路，不保证

是的，可以了。种子下载后也上传了，但是没自动清除下载文件夹。
