### ISSUE TITLE
file browser界面密码错误

### ISSUE THREAD

**Issue by jimodeniuren** [666wcy/ARPT-Bot#35]
正确输入用户名admin与Aria2_secret后始终显示用户名或密码错误

**Comment by 666wcy** [comment]
![image](https://user-images.githubusercontent.com/40867688/149508217-d9ab801f-9583-4a1b-964f-822f1359430e.png)
无法复现你的错误

**Comment by jimodeniuren** [comment]
破案了，我拉的镜像是2.0.8，删了重拉2.0.9解决了

**Comment by 666wcy** [comment]
最新版为2.1.0,0.9有概率因为第三方库的原因启动失败
