### ISSUE TITLE
几点问题和建议

### ISSUE THREAD

**Issue by Jonathon52306** [666wcy/ARPT-Bot#36]
1. 如果是视频转发过去会显示名字None 但是实际上下载的文件名是video_开头的，全是None不好区分，能否先获取文件名然后在动态刷新的过程中显示该文件名？
2. 多个视频或文件一起转发，有时只能读取到第一个，目前看下来文件的话原发送者相同时6-7个文件一起转发只有少部分时候才会读取问题，但是如果是视频的话一次只能发一个，否则100%复现。
3. 这个命令对图片无响应 会自动识别为以图搜图
4. 建议安排任务队列依次下载，而不是让所有的文件/视频同时下载，会卡顿甚至直接卡死。
5. 建议rclonecopy添加任务进度或任务或任务完成提示，不然看着像死机了一样。
6. 下载种子文件/磁力链大文件不上传，小文件也有时候不上传。

**Comment by 666wcy** [comment]
![image](https://user-images.githubusercontent.com/40867688/154800157-4ceaf315-4558-4a91-9cbf-dd86bfb15975.png)
rclonecopy的话下载进度是有的
不上传的原因可能是rclone的问题，或者是你映射的路径没有设置权限
