### ISSUE TITLE
请教一下关于ascii2d搜图功能的Cloudflare问题

### ISSUE THREAD

**Issue by NagaseYami** [666wcy/ARPT-Bot#41]
我自己也有在练习写一些机器人，并且参考了您的代码，非常感谢您的这个项目
前段时间ascii2d上了Cloudflare，我就尝试使用[VeNoMouS/cloudscraper](https://github.com/VeNoMouS/cloudscraper)看能不能解决5秒盾问题，结果发现第一次能成功但是第二次开始基本上就会被要求做CAPTCHA

https://github.com/666wcy/ARPT-Bot/blob/36dc2ee63ddc94e186c9e5de94c94a5e91679691/bot/modules/photo.py#L140-L146
我看了一下您的项目，发现您的项目只用了一行requests就解决了
我复制粘贴了这一段代码并执行，得到的却是403
但是telegram上看到的一些使用该代码的bot的ascii2d功能任然能够正常运作
请问您是怎么解决的？

**Comment by 666wcy** [comment]
很遗憾，我没有对cloudflare做任何处理措施。
在我写代码的时候还没有上5秒盾。

**Comment by NagaseYami** [comment]
其实我是从Telegram的一个ID为`soutubot`的机器人那里看到了您的项目链接，我一开始以为只是有人部署了您的机器人项目。不过考虑到它目前还能正常使用ascii2d，也许它是基于您的项目改过的。看来是问错地方了
感谢您的回复

**Comment by NagaseYami** [comment]
最终我还是使用了[Headless Browser](https://github.com/go-rod/rod)解决了5秒盾的问题。（我的机器人是用golang写的）
