### ISSUE TITLE
求教rclone盘符和上传文件夹怎么填

### ISSUE THREAD

**Issue by Dragon-son** [666wcy/ARPT-Bot#7]
rclone配置是起的名是od
挂载为本地磁盘时设置的onedrive文件夹是movie,本地文件夹是/mnt/onedrive，求教怎么填remote和upload,试了很多种都没有挂载成功，大佬能解答一下嘛

**Comment by 666wcy** [comment]
盘符填写你设置rclone时对应的remote
upload填od里的路径，例如od根目录中的mover文件夹就填mover，mover文件夹里的子文件夹test，就填mover/test
