### ISSUE TITLE
请问https://my.telegram.org这里注册应用的各种参数怎么填

### ISSUE THREAD

**Issue by 12123ads** [666wcy/ARPT-Bot#9]

**Comment by 666wcy** [comment]
项目对填写信息没有要求，只要你最终申请得到一个 api id 和api hash即可

**Comment by 12123ads** [comment]
![jietu.png](https://store.heytapimage.com/cdo-portal/feedback/202108/13/25d08850e10c4cf98e5f560aa76002f8.png)
这个一直报错

**Comment by 666wcy** [comment]
https://stackoverflow.com/questions/53340549/error-telegram-id-and-hash-incorrect-app-name33

**Comment by 12123ads** [comment]
![jietu.png](https://store.heytapimage.com/cdo-portal/feedback/202108/13/b44c6adbcbe91f9eca40a50135b8b57f.png)
这我按他的示例也不行阿

**Comment by 666wcy** [comment]
非项目问题，请自行搜索解决方案

**Comment by h7ml** [comment]
> ![jietu.png](https://camo.githubusercontent.com/4c893074f366513b8698ee0120278a96385882b791a771c040768b966b8ad1f0/68747470733a2f2f73746f72652e686579746170696d6167652e636f6d2f63646f2d706f7274616c2f666565646261636b2f3230323130382f31332f62343463366164626362653931663965636134306135303133356238623537662e706e67)
> 这我按他的示例也不行阿

隐身模式打开即可
